NumPy

# Why use NumPy? NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further. 

# NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

#تعد مصفوفات NumPy أسرع وأكثر إحكاما من قوائم Python. المصفوفة تستهلك ذاكرة أقل وهي ملائمة للاستخدام. يستخدم NumPy ذاكرة أقل بكثير لتخزين البيانات ويوفر آلية لتحديد أنواع البيانات. هذا يسمح بتحسين الكود إلى أبعد من ذلك بعض الشيء.  


# What is an array?
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.
ما هي المصفوفة؟ 
المصفوفة هي بنية بيانات مركزية لمكتبة NumPy. المصفوفة عبارة عن شبكة من القيم وتحتوي على معلومات حول البيانات الأولية وكيفية تحديد موقع العنصر وكيفية تفسير العنصر. يحتوي على شبكة من العناصر التي يمكن فهرستها بطرق مختلفة . العناصر كلها من نفس النوع ، يشار إليها باسم المصفوفة dtype.


In [ ]:
pip install numpy # install numpy  تثبيت مكتبه نامباي

In [ ]:
import numpy as np # import numpy as np  استدعاء مكتبه نامباي, واختصار اسمها بالحرف np  لاستخدامها بشكل مباشر دون كتابتها كامله كل مره 

print(np.__version__)  # print numpy version  طباعه اصدار مكتبه نامباي

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6]) # create array   انشاء مصفوفه ذات بعد واحد  
print(a) # print array  (a) فقط ويطبعها بشكل مباشر طباعه المصفوفه ممكن ان نكتب ايضا

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) # create array   انشاء مصفوفه ذات بعدين
a # print array  (a) فقط ويطبعها بشكل مباشر طباعه المصفوفه ممكن ان نكتب ايضا 


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

 # كيفية إنشاء مصفوفة أساسية في NumPy؟ 
 # This section covers np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype and itemsize. 

In [22]:
a = np.array([1, 2, 3]) # create 1D array   انشاء مصفوفه ذات بعد واحد 
b = np.array(([1, 2, 3],[4, 5, 6])) # create 2D array   انشاء مصفوفه ذات بعدين
c = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
              [[19, 20, 21], [22, 23, 24], [25, 26, 27]]]) # create 3D array  انشاء مصفوفه ذات ثلاث ابعاد 

print(a)
print(a.ndim) # print array dimension  طباعه عدد الابعاد للمصفوفه
print(b)
print(b.ndim) # print array dimension  طباعه عدد الابعاد للمصفوفه
print(c)
print(c.ndim) # print array dimension  طباعه عدد الابعاد للمصفوفه



[1 2 3]
1
[[1 2 3]
 [4 5 6]]
2
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
3


In [25]:
np.zeros(3) # create array of zeros  انشاء مصفوفه من الصفر

array([0., 0., 0.])

In [26]:
np .zeros((2, 3)) # create array of zeros  انشاء مصفوفه من الصفر

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(3) # create array of ones  انشاء مصفوفه من الواحد

In [28]:
np.ones((2, 3)) # create array of ones  انشاء مصفوفه من الواحد

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.full((2, 3), 5) # create array of 5  انشاء مصفوفه من الخمسه

array([[5, 5, 5],
       [5, 5, 5]])

In [31]:
np.empty((2, 3)) # create empty array  انشاء مصفوفه فارغه 


array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.arange(10) # create array of 0 to 9  انشاء مصفوفه من الصفر الى التسعه 


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(1, 10) # create array of 1 to 9  انشاء مصفوفه من الواحد الى التسعه

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(1, 10, 2) # create array of 1 to 9 with step 2  انشاء مصفوفه من الواحد الى التسعه بخطوه 2


array([1, 3, 5, 7, 9])

In [43]:
np.linspace(0, 10, 5) # create array of 5 numbers from 0 to 10  انشاء مصفوفه من خمسه ارقام من الصفر الى الواحد

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [44]:
np.linspace(0, 10, 5, endpoint=False) # create array of 5 numbers from 0 to 10 without endpoint  انشاء مصفوفه من خمسه ارقام من الصفر الى الواحد بدون اخر رقم

array([0., 2., 4., 6., 8.])

In [45]:
x = np.ones(2, dtype=np.int64) # create array of ones with dtype int64  انشاء مصفوفه من الواحد بنوع البيانات int64
x 

array([1, 1], dtype=int64)

In [47]:
x = np.ones(2, dtype=np .float64) # create array of ones with dtype float64  انشاء مصفوفه من الواحد بنوع البيانات float64
x

array([1., 1.])

# كيف تعرف شكل وحجم المصفوفة؟ 
# يغطي هذا القسم  ndarray.ndim ،ndarray.size ndarray.shape . 

In [50]:
array= np.array([[[0, 1, 2, 3],
                  [4, 5, 6, 7]],

                  [[0, 1, 2, 3],
                   [4, 5, 6, 7]],

                  [[0 ,1 ,2, 3],
                  [4, 5, 6, 7]]]) # create 3D array  انشاء مصفوفه ذات ثلاث ابعاد

print (array)  # print array  (array) فقط ويطبعها بشكل مباشر طباعه المصفوفه ممكن ان نكتب ايضا

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [54]:
array.shape # print array shape  طباعه شكل المصفوفه

(3, 2, 4)

In [53]:
array.size # print array size  طباعه حجم المصفوفه

24

In [52]:
array.ndim # print array dimension  طباعه عدد الابعاد للمصفوفه 

3

 # اضافة وازالة وفرز العناصر في المصفوفة
# يغطي هذا القسم  np.append(), np.insert(), np.delete(), np.sort() and np.unique() , np.sort() ،np.concatenate()

In [56]:
x = np.array([2, 1, 5, 3, 7, 4, 6, 8]) # create array  انشاء مصفوفه 
x.sort() # sort array  ترتيب المصفوفه
x # print sorted array  طباعه المصفوفه المرتبه

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
a = np.array([1, 2, 3, 4]) # create array  انشاء مصفوفه
b = np.array([5, 6, 7, 8]) # create array  انشاء مصفوفه
np.concatenate((a, b)) # concatenate arrays  اضافه المصفوفتين

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
x = np.array([[1, 2], [3, 4]]) # create array  انشاء مصفوفه
y = np.array([[5, 6]])  # create array  انشاء مصفوفه 

In [60]:
np.concatenate((x, y), axis=0)  # concatenate arrays  اضافه المصفوفتين 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
np.concatenate((x, y .T), axis=1)  # concatenate arrays  اضافه المصفوفتين

array([[1, 2, 5],
       [3, 4, 6]])

# هل يمكنك إعادة تشكيل مصفوفة؟ 
# يغطي هذا القسم  arr.reshape() 
# Can you reshape an array?  
# This section covers arr.reshape()

In [66]:
x = np.arange(6) # create array  انشاء مصفوفه 
x

array([0, 1, 2, 3, 4, 5])

In [68]:
x = x.reshape((2, 3)) # reshape array  تغيير شكل المصفوفه 
x

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
x = np.reshape(a, newshape=(1, 6)) # reshape array  تغيير شكل المصفوفه 
x

array([[0, 1, 2, 3, 4, 5]])